//auth
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const SAVE_ERROR_SUCCESS = 'SAVE_ERROR_SUCCESS';
export const SAVE_ERROR = 'SAVE_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const SAVE_ACCOUNT_SUCCESS = 'SAVE_ACCOUNT_SUCCESS';
export const SAVE_ACCOUNT_ERROR = 'SAVE_ACCOUNT_ERROR';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_ERROR = 'SAVE_PROFILE_ERROR';
export const LOGIN_EXPIRED_SESSION = 'LOGIN_EXPIRED_SESSION';

//marks
export const GET_MARKS_SUCCESS = 'GET_MARKS_SUCCESS';
export const GET_MARKS_ERROR = 'GET_MARKS_SUCCESS';
export const GET_MARK_SUCCESS = 'GET_MARK_SUCCESS';
export const GET_MARK_ERROR = 'GET_MARK_ERROR';
export const SAVE_MARKS_SUCCESS = 'SAVE_MARKS_SUCCESS';
export const SAVE_MARKS_ERROR = 'SAVE_MARKS_ERROR';
export const SAVE_MARKS_FAILED_RANGE = 'SAVE_MARKS_FAILED_RANGE';
export const SAVE_MARKS_FAILED_RANGE_ERROR = 'SAVE_MARKS_FAILED_RANGE_ERROR';
export const CLEAR_MARK = 'CLEAR_MARK';
export const CLEAR_MARK_MESSAGES = 'CLEAR_MARK_MESSAGES';
export const MARK_EXPIRED_SESSION = 'MARK_EXPIRED_SESSION';

//report
export const GET_REPORT_DATE_SUCCESS = 'GET_REPORT_DATE_SUCCESS';
export const GET_REPORT_DATE_ERROR = 'GET_REPORT_DATE_ERROR';
export const GET_REPORT_INDIVIDUAL_SUCCESS = 'GET_REPORT_INDIVIDUAL_SUCCESS';
export const GET_REPORT_INDIVIDUAL_ERROR = 'GET_REPORT_INDIVIDUAL_ERROR';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const CLEAR_REPORT = 'CLEAR_REPORT';
export const CLEAR_REPORT_MESSAGES = 'CLEAR_REPORT_MESSAGES';
export const CLEAR_INDIVIDUAL_REPORT = 'CLEAR_INDIVIDUAL_REPORT';
export const REPORT_EXPIRED_SESSION = 'REPORT_EXPIRED_SESSION';

//incidents
export const SAVE_INCIDENT_SUCCESS = 'SAVE_INCIDENT_SUCCESS';
export const SAVE_INCIDENT_ERROR = 'SAVE_INCIDENT_ERROR';
export const GET_INCIDENT_SUCCESS = 'GET_INCIDENT_SUCCESS';
export const GET_INCIDENT_ERROR = 'GET_INCIDENT_ERROR';
export const CLEAR_INCIDENT_MESSAGE = 'CLEAR_INCIDENT_MESSAGE';
export const CLEAR_INCIDENT = 'CLEAR_INCIDENT';
export const INCIDENT_EXPIRED_SESSION = 'INCIDENT_EXPIRED_SESSION';

//alerts
export const SEND_ALERT_SUCCESS = 'SEND_ALERT_SUCCESS';
export const SEND_ALERT_ERROR = 'SEND_ALERT_ERROR';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const ALERT_EXPIRED_SESSION = 'ALERT_EXPIRED_SESSION';

//supervysors
export const GET_SUPERVYSORS_SUCCESS = 'GET_SUPERVYSORS_SUCCESS';
export const GET_SUPERVYSORS_ERROR = 'GET_SUPERVYSORS_ERROR';
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS';
export const GET_FORM_ERROR = 'GET_FORM_ERROR';
export const SAVE_SUPERVYSOR_SUCCESS = 'SAVE_SUPERVYSOR_SUCCESS';
export const SAVE_SUPERVYSOR_ERROR = 'SAVE_SUPERVYSOR_ERROR';
export const CLEAR_SUPERVYSOR = 'CLEAR_SUPERVYSOR';
export const CLEAR_SUPERVYSOR_MESSAGES = 'CLEAR_SUPERVYSOR_MESSAGES';

//documents
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const GET_DOCUMENTS_ERROR = 'GET_DOCUMENTS_ERROR';
export const CLEAR_DOCUMENTS = 'CLEAR_DOCUMENTS';

//notifications
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS';
export const SUBSCRIPTION_ERROR = 'SUBSCRIPTION_ERROR';
export const UNSUBSCRIPTION_SUCCESS = 'UNSUBSCRIPTION_SUCCESS';
export const UNSUBSCRIPTION_ERROR = 'UNSUBSCRIPTION_ERROR';
export const LOAD_SUBSCRIPTION_SUCCESS = 'LOAD_SUBSCRIPTION_SUCCESS';
export const LOAD_SUBSCRIPTION_ERROR = 'LOAD_SUBSCRIPTION_ERROR';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

//assets
export const SAVE_ASSET_SUCCESS = 'SAVE_ASSET_SUCCESS';
export const SAVE_ASSET_ERROR = 'SAVE_ASSET_ERROR';
export const UPDATE_ASSET_SUCCESS = 'UPDATE_ASSET_SUCCESS';
export const UPDATE_ASSET_ERROR = 'UPDATE_ASSET_ERROR';
export const GET_ASSETS_SUCCESS = 'GET_ASSETS_SUCCESS';
export const GET_ASSETS_ERROR = 'GET_ASSETS_ERROR';
export const DISABLE_ASSET_SUCCESS = 'DISABLE_ASSET_SUCCESS';
export const DISABLE_ASSET_ERROR = 'DISABLE_ASSET_ERROR';
export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS';
export const DELETE_ASSET_ERROR = 'DELETE_ASSET_ERROR';
export const CHANGE_ASSET_SUCCESS = 'CHANGE_ASSET_SUCCESS';
export const CHANGE_ASSET_ERROR = 'CHANGE_ASSET_ERROR';
export const CLIENTS_ASSET_SUCCESS = 'CLIENTS_ASSET_SUCCESS';
export const CLIENTS_ASSET_ERROR = 'CLIENTS_ASSET_ERROR';
export const CLEAR_ASSETS_MESSAGES = 'CLEAR_ASSETS_MESSAGES';
export const CLEAR_ASSETS = 'CLEAR_NOTIFICATIONS';
